spring:
  application:
    name: coffee
  datasource:
    url: jdbc:mysql://localhost:3306/coffee
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
