spring:
  application:
    name: coffee
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/coffee?connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}
    hikari:
      connection-init-sql: SET time_zone = '+00:00'
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:500ms}
      timeout: ${REDIS_TIMEOUT:500ms}
